In [ ]:
#import relevant libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as sk
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
# Uploading my dataset
df = pd.read_csv('/content/IRIS.csv')

In [ ]:
# performing a .head function
# displaying the first few rows of a data set
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           NaN          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
# performing a .describe function
# displaying the statistical summary of the numer column in my data set
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    144.000000   143.000000    142.000000   150.000000
mean       5.867361     3.053846      3.819718     1.198667
std        0.830522     0.430324      1.753143     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.400000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
# performing a .info function
# understanding the structure and properties of my data set
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  144 non-null    float64
 1   sepal_width   143 non-null    float64
 2   petal_length  142 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
# performing a . shape function
# This lets us know the number of rows and columns in our data set
df.shape

(150, 5)

In [ ]:
# performing a . shape[0] function
# to know only the number of rows
df.shape[0]

150

In [ ]:
# performing a .shape[1]
# to know the numer of columns only
df.shape[1]

5

In [ ]:
# performing a .isna count
# checking the cells in the data set or missing values
df.isna()



sepal_length  sepal_width  petal_length  petal_width  species
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3            True        False         False        False    False
4           False        False         False        False    False
..            ...          ...           ...          ...      ...
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        False    False
148         False        False         False        False    False
149         False        False          True        False    False

[150 rows x 5 columns]

In [ ]:
# performing a .isna  sum count
# checking the cells in the data set for the count of  missing values
df.isna().sum()

sepal_length    6
sepal_width     7
petal_length    8
petal_width     0
species         0
dtype: int64

In [ ]:
# encoding the species column to binary
le = LabelEncoder()
df['species'] = le.fit_transform(df['species'])

In [ ]:
#Tryin to see if species has been encoded successfully
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           NaN          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [ ]:
# fill in the missing values for sepal length using median
df['sepal_length'].fillna(df['sepal_length'].median(), inplace=True)


<ipython-input-15-fb247ee6b7eb>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sepal_length'].fillna(df['sepal_length'].median(), inplace=True)


In [ ]:
# fill in the missing values for sepal width using median
df['sepal_width'].fillna(df['sepal_width'].median(), inplace=True)



<ipython-input-18-ad7ab9580c3b>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sepal_width'].fillna(df['sepal_width'].median(), inplace=True)


In [ ]:
# fill in the missing values for petal lenghth using median
df['petal_length'].fillna(df['petal_length'].median(), inplace=True)


<ipython-input-21-61b187671592>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['petal_length'].fillna(df['petal_length'].median(), inplace=True)


In [ ]:
# performing a .isna.sum couunt after
# filling missing values
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
# choosing featues for the train and test data
'petal_length','sepal_width'
y = df['species']

In [ ]:
#feature scaling petal length ,sepal width
scaler = StandardScaler()
X = scaler.fit_transform(df[['petal_length', 'sepal_width']])

In [ ]:
# splitting the data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
len(X_train)

120

In [ ]:
len(X_test)

30

In [ ]:
len(y_train)

120

In [ ]:
len(y_test)

30

In [ ]:
X_train

array([[-1.67221145,  1.30995   ],
       [-1.37890963,  3.21996215],
       [ 0.32224093,  0.11619241],
       [-1.32024927,  0.83244696],
       [-1.49623036,  0.35494392],
       [ 0.67420312, -1.31631671],
       [ 0.3809013 ,  0.35494392],
       [-1.37890963,  1.07119848],
       [-1.43757   ,  1.30995   ],
       [-1.37890963,  2.50370759],
       [ 0.73286349, -0.83881367],
       [ 0.3809013 ,  0.83244696],
       [ 0.49822203,  0.11619241],
       [-1.49623036, -0.12255911],
       [-1.37890963,  1.54870152],
       [-0.08838162, -0.12255911],
       [ 0.73286349, -0.60006215],
       [ 0.96750494,  0.11619241],
       [ 0.32224093, -0.12255911],
       [ 1.31946713,  1.30995   ],
       [ 0.20492021, -0.36131063],
       [ 1.61276895, -0.12255911],
       [ 0.3809013 , -0.12255911],
       [-1.43757   ,  1.07119848],
       [ 1.67142931, -0.60006215],
       [ 0.14625984, -0.83881367],
       [-1.43757   ,  0.83244696],
       [-1.49623036,  1.07119848],
       [-1.14426817,

In [ ]:
X_test

array([[ 0.49822203, -0.60006215],
       [-1.2615889 ,  1.78745304],
       [ 1.78875004, -1.07756519],
       [ 0.3809013 , -0.36131063],
       [ 0.55688239, -0.60006215],
       [ 0.32224093,  0.83244696],
       [-0.14704198, -0.36131063],
       [ 0.73286349,  0.11619241],
       [ 0.3809013 , -2.03257126],
       [ 0.02893911, -0.83881367],
       [ 0.73286349,  0.35494392],
       [ 0.32224093, -0.12255911],
       [-1.49623036,  1.07119848],
       [ 0.32224093,  0.11619241],
       [-1.37890963,  1.78745304],
       [ 0.49822203,  0.59369544],
       [ 1.14348604, -0.12255911],
       [ 0.02893911, -1.31631671],
       [ 0.3809013 , -0.60006215],
       [ 1.02616531, -0.60006215],
       [-1.32024927, -0.12255911],
       [ 0.61554276, -0.12255911],
       [-1.32024927,  0.83244696],
       [ 1.02616531, -0.60006215],
       [ 1.49544822,  1.78745304],
       [ 0.79152385, -0.12255911],
       [ 1.14348604, -1.31631671],
       [ 1.2021464 ,  0.35494392],
       [-1.43757   ,

In [ ]:
# fitting the logistics regression model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
# predict the type of species using 'petal_length','sepal_width'
#and give an outcome
y_pred = model.predict(X_test)
y_pred
log = round(model.score(X_test, y_test)* 100, 2)
log

90.0

In [ ]:
# predict accuracy
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9

In [ ]:
#showing  the first five predicted species values."
y_pred[:5]

array([1, 0, 2, 1, 1])